######################################################################
# Automatically generated by qmake (3.0) mar ott 10 14:57:07 2017
######################################################################

TEMPLATE = app
TARGET = ComplianceRos
INCLUDEPATH += .

# Input
HEADERS += custom_controller/include/custom_controller/actuator_position_controller1.h \
           custom_controller/include/custom_controller/actuator_position_controller4.h \
           custom_controller/include/custom_controller/actuator_position_controller_all.h \
           custom_controller/include/custom_controller/actuator_position_controller_classes.h \
           custom_controller/include/custom_controller/controller_utils.h \
    custom_controller/include/custom_controller/actuator_velocity_controller.h
SOURCES += custom_controller/src/actuator_position_controller1.cpp \
           custom_controller/src/actuator_position_controller4.cpp \
           custom_controller/src/actuator_position_controller_all.cpp \
           custom_controller/src/actuator_position_controller_classes.cpp \
           custom_controller/src/controller_utils.cpp \
    custom_controller/src/actuator_velocity_controller.cpp
