#!/usr/bin/env python

import roslib
roslib.load_manifest('centauro_control')
#from std_msgs.msg import Float64
from custom_messages.msg import CustomCmnd
from sensor_msgs.msg import JointState
import rospy
import math

if __name__ == '__main__':
	rospy.init_node('setActuators')

	#a = JointState()
	a = CustomCmnd()
	b = JointState()
	b.name = ["j_wheel_hip_1",
			  "j_wheel_hip_2",
			  "j_wheel_hip_3",
			  "j_wheel_hip_4",

			  "j_wheel_knee_1",
			  "j_wheel_knee_2",
			  "j_wheel_knee_3",
			  "j_wheel_knee_4",]


	rate = rospy.Rate(1000.0)
	command = rospy.Publisher('/centauro/position_controller/command', CustomCmnd, queue_size=1)
#!	command = rospy.Publisher('/centauro/position_controller/command', JointState, queue_size=1)
	wheel_command = rospy.Publisher('/centauro/wheels_controller/command', JointState, queue_size=1)
	start = rospy.get_rostime()

	while not rospy.is_shutdown():
		time = rospy.get_rostime()
		time_sec = time.to_sec() -  start.to_sec()

		a.position = [
        0.,				#torso_yaw - 0

        0.2,				#j_arm1_1 - 1
        0.3,				#j_arm1_2 - 2
        0.5,				#j_arm1_3 - 3
        -1.2,				#j_arm1_4 - 4
        0.7,				#j_arm1_5 - 5
        -0.5,				#j_arm1_6 - 6
        0.5,				#j_arm1_7 - 7

        -0.2,				#j_arm2_1 - 8
        0.3,				#j_arm2_2 - 9
        -0.5,				#j_arm2_3 - 10
        1.0,				#j_arm2_4 - 11
        -0.7,				#j_arm2_5 - 12
        0.5,				#j_arm2_6 - 13
        0.5,				#j_arm2_7 - 14

        0.8,            #hip_y_1 - 15
        0.8,            #hip_y_2 - 16
        -0.8,			#hip_y_3 - 17
        -0.8,			#hip_y_4 - 18

        0.9,			#hip_p_1 - 19
        0.9,			#hip_p_2 - 20
        0.9,			#hip_p_3 - 21
        0.9,			#hip_p_4 - 22

        -0.9,			#knee_p_1 - 23
        -0.9,			#knee_p_2 - 24
        -0.9,			#knee_p_3 - 25
        -0.9,]			#knee_p_4 - 26



		b.position = [	0.0*rospy.get_time(),		#"j_wheel_hip_1"
			  	0.0*rospy.get_time(),		#"j_wheel_hip_1"
			  	0.0*rospy.get_time(),		#"j_wheel_hip_3"
			  	0.0*rospy.get_time(),		#"j_wheel_hip_4",

			  	0.0*rospy.get_time(),		#"j_wheel_knee_1",
			  	0.0*rospy.get_time(),		#"j_wheel_knee_2",
			  	0.0*rospy.get_time(),		#"j_wheel_knee_3",
			  	0.0*rospy.get_time(),]		#"j_wheel_knee_4"
#		a.header.stamp = time
		command.publish(a)
		wheel_command.publish(b)
		rate.sleep()




