#!/usr/bin/env python

import roslib
roslib.load_manifest('centauro_control')
#from std_msgs.msg import Float64
from custom_messages.msg import CustomCmnd
from sensor_msgs.msg import JointState
import rospy
import math

if __name__ == '__main__':
	rospy.init_node('setActuators')

	#a = JointState()
	a = CustomCmnd()
	b = CustomCmnd()


	rate = rospy.Rate(1000.0)
	wheel_command = rospy.Publisher('/centauro/velocity_controller/command', CustomCmnd, queue_size=1)
	start = rospy.get_rostime()

	while not rospy.is_shutdown():
		time = rospy.get_rostime()
		time_sec = time.to_sec() -  start.to_sec()

		b.velocity = [  1.0,		#"j_wheel_1"
			  	-1.0,		#"j_wheel_2"
			  	1.0,		#"j_wheel_3"
			  	-1.0,		#"j_wheel_4",
                                0.5
                ]
		#"j_wheel_knee_4"
#		a.header.stamp = time
		#command.publish(a)
		wheel_command.publish(b)
		rate.sleep()




