#!/usr/bin/env python

import numpy as np
import rbdl
import roslib
roslib.load_manifest('custom_controller')
import rospy

model = rbdl.Model()

if __name__ == '__main__':
	rospy.init_node('saveData')
	model = rbdl.Model()
    
