#!/usr/bin/env python

import roslib
roslib.load_manifest('centauro_control')
from std_msgs.msg import Float64
from sensor_msgs.msg import JointState
import rospy
import math

if __name__ == '__main__':
	rospy.init_node('setActuators')
	
	a = JointState()
	a.name = ["hip_y_1",
			  "hip_y_2",
			  "hip_y_3",
			  "hip_y_4",
			  
			  "hip_p_1",
			  "hip_p_2",
			  "hip_p_3",
			  "hip_p_4",
			  
			  "knee_p_1",
			  "knee_p_2",
			  "knee_p_3",
			  "knee_p_4",
			  
			  "torso_yaw",
			  
			  "j_arm1_1",
			  "j_arm1_2",
			  "j_arm1_3",
			  "j_arm1_4",
			  "j_arm1_5",
			  "j_arm1_6",
			  "j_arm1_7",
			  
			  "j_arm2_1",
			  "j_arm2_2",
			  "j_arm2_3",
			  "j_arm2_4",
			  "j_arm2_5",
			  "j_arm2_6",
			  "j_arm2_7"]
	
	b = JointState()
	b.name = ["j_wheel_hip_1",
			  "j_wheel_hip_2",
			  "j_wheel_hip_3",
			  "j_wheel_hip_4",
			  
			  "j_wheel_knee_1",
			  "j_wheel_knee_2",
			  "j_wheel_knee_3",
			  "j_wheel_knee_4",]
	
	
	rate = rospy.Rate(1000.0)
	command = rospy.Publisher('/centauro/pd_controller/command', JointState, queue_size=1)
	wheel_command = rospy.Publisher('/centauro/pd_wheels_controller/command', JointState, queue_size=1)

	while not rospy.is_shutdown():
		a.position = [
				0,				#torso_yaw - 0
					   
				0,				#j_arm1_1 - 1
				0,				#j_arm1_2 - 2
				0,				#j_arm1_3 - 3
				0,				#j_arm1_4 - 4
				0,				#j_arm1_5 - 5
				0,				#j_arm1_6 - 6
				0,				#j_arm1_7 - 7
					   
				1,				#j_arm2_1 - 8
				0,				#j_arm2_2 - 9
				1,				#j_arm2_3 - 10
				0,				#j_arm2_4 - 11
				0,				#j_arm2_5 - 12
				0,				#j_arm2_6 - 13
				0,				#j_arm2_7 - 14

				0.6*math.pi/4.0,			#hip_y_1 - 15
				0.6*math.pi/4.0,			#hip_y_2 - 16
				-0.6*math.pi/4.0,			#hip_y_3 - 17
				-0.6*math.pi/4.0,			#hip_y_4 - 18
					  
				math.pi/8.0,			#hip_p_1 - 19
				math.pi/6.0,			#hip_p_2 - 20
				math.pi/6.0,			#hip_p_3 - 21
				math.pi/6.0,			#hip_p_4 - 22
					  
				-math.pi/6.0,			#knee_p_1 - 23
				-math.pi/6.0,			#knee_p_2 - 24
				-math.pi/6.0,			#knee_p_3 - 25
				-math.pi/6.0,]			#knee_p_4 - 26

		b.position = [	0.4*rospy.get_time(),		#"j_wheel_hip_1"
			  	0.4*rospy.get_time(),		#"j_wheel_hip_1"
			  	0.4*rospy.get_time(),		#"j_wheel_hip_3"
			  	0.4*rospy.get_time(),		#"j_wheel_hip_4",
			  
			  	0.4*rospy.get_time(),		#"j_wheel_knee_1",
			  	0.4*rospy.get_time(),		#"j_wheel_knee_2",
			  	0.4*rospy.get_time(),		#"j_wheel_knee_3",
			  	0.4*rospy.get_time(),]		#"j_wheel_knee_4"

		command.publish(a)
		wheel_command.publish(b)
		rate.sleep()
	
	
	
	
